name: Run Simulation
on:
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install numpy matplotlib

      - name: Run the simulation
        run: python project.py

      - name: Upload graph
        uses: actions/upload-artifact@v4
        with:
          name: simulation-result
          path: result.png